<?php

declare(strict_types=1);

use App\Enums\WorkSupportStatus;
use App\Models\PcUnit;
use App\Models\QrCode;
use App\Models\QrScanLog;
use App\Models\User;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * WP-2.6b Stage A — the schema itself (SRS DR-020, FR-WSR-002/004/008/014,
 * FR-MNT-012; SDD DD-50/DD-51/DD-54).
 *
 * **These tests speak SQL, not Eloquent, on purpose.** The models, the
 * lifecycle service and the policies arrive in later stages; what has to be true
 * *now* is that the database refuses bad data on its own — DR-020 requires a
 * decline without a reason to be "refused at the database level as well as the
 * application level", and a constraint tested only through a model that also
 * validates proves nothing about the database. Raw inserts are the only way to
 * see the constraint fire.
 *
 * Each negative case asserts on the **constraint name**, so a test cannot pass
 * because some *other* rule happened to reject the row.
 */
beforeEach(function (): void {
    $this->pcUnit = PcUnit::factory()->create();
    $this->technician = User::factory()->create();
});

/**
 * A minimal valid request row. Overrides are merged so each test states only
 * the one thing it is bending.
 *
 * @param  array<string, mixed>  $overrides
 */
function wsrRow(array $overrides = []): array
{
    return [
        'pc_unit_id' => test()->pcUnit->id,
        'technician_id' => test()->technician->id,
        'explanation' => 'The power supply failed and I need a replacement to finish.',
        'status' => WorkSupportStatus::Submitted->value,
        'created_at' => now(),
        'updated_at' => now(),
        ...$overrides,
    ];
}

/* ------------------------------------------------------- qr_scan_logs (M1) */

it('gives every scan log a unique uuid generated by the database', function (): void {
    expect(Schema::hasColumn('qr_scan_logs', 'uuid'))->toBeTrue()
        ->and(Schema::hasColumn('qr_scan_logs', 'user_agent'))->toBeTrue();

    // Inserted without a uuid: the column default has to supply one, because a
    // row written outside Eloquent must still have a public identity.
    $id = DB::table('qr_scan_logs')->insertGetId([
        'scan_result' => 'success',
        'scanned_at' => now(),
    ]);

    $uuid = DB::table('qr_scan_logs')->where('id', $id)->value('uuid');

    expect($uuid)->not->toBeNull()
        ->and($uuid)->toMatch('/^[0-9a-f-]{36}$/');
});

it('refuses two scan logs sharing a uuid', function (): void {
    $first = QrScanLog::factory()->create();

    expect(fn () => DB::table('qr_scan_logs')->insert([
        'uuid' => $first->fresh()->uuid,
        'scan_result' => 'success',
        'scanned_at' => now(),
    ]))->toThrow(QueryException::class, 'qr_scan_logs_uuid_unique');
});

it('binds a scan to at most one maintenance record by column cardinality', function (): void {
    // The FR-MNT-012 guarantee is structural, not procedural: `maintenance_record_id`
    // is a single nullable FK, so a second binding overwrites rather than adds.
    // Asserting the shape here is what lets the Stage E service rely on it.
    expect(Schema::hasColumn('qr_scan_logs', 'maintenance_record_id'))->toBeTrue();

    $columns = DB::selectOne(<<<'SQL'
        SELECT count(*) AS n
        FROM information_schema.columns
        WHERE table_name = 'qr_scan_logs' AND column_name = 'maintenance_record_id'
    SQL);

    expect((int) $columns->n)->toBe(1);
});

it('indexes scans by code and time together for the per-code lookup', function (): void {
    $index = DB::selectOne(<<<'SQL'
        SELECT indexdef FROM pg_indexes
        WHERE tablename = 'qr_scan_logs' AND indexname = 'qr_scan_logs_code_scanned_index'
    SQL);

    expect($index)->not->toBeNull()
        ->and($index->indexdef)->toContain('qr_code_id')
        ->and($index->indexdef)->toContain('scanned_at');
});

it('leaves the scan log reachable after its qr code is deleted', function (): void {
    // ON DELETE SET NULL was baselined; the new columns must not have changed
    // it, or revoking-by-deletion would silently destroy scan history.
    $qr = QrCode::factory()->create(['pc_unit_id' => $this->pcUnit->id, 'asset_id' => null]);
    $log = QrScanLog::factory()->create(['qr_code_id' => $qr->id]);

    $qr->delete();

    $row = DB::table('qr_scan_logs')->where('id', $log->id)->first();

    expect($row)->not->toBeNull()
        ->and($row->qr_code_id)->toBeNull()
        ->and($row->uuid)->not->toBeNull();
});

/* ------------------------------------------- work_support_requests (M2/DR-020) */

it('accepts a well-formed work support request', function (): void {
    $id = DB::table('work_support_requests')->insertGetId(wsrRow());

    $row = DB::table('work_support_requests')->where('id', $id)->first();

    expect($row->uuid)->not->toBeNull()
        ->and($row->status)->toBe(WorkSupportStatus::Submitted->value)
        ->and($row->pc_unit_id)->toBe($this->pcUnit->id)
        ->and($row->decided_at)->toBeNull();
});

/*
 * Tabs and newlines are in this dataset because bare `btrim()` does **not**
 * strip them — an earlier draft of this constraint used `btrim(explanation) <> ''`
 * and let `"\t\n"` through, while PHP's `trim()` rejected it one layer up. The
 * database has to refuse the same set the application refuses, or DR-020's
 * "at the database level as well as" is decorative.
 */
it('refuses a request whose explanation is blank', function (string $explanation): void {
    expect(fn () => DB::table('work_support_requests')->insert(wsrRow(['explanation' => $explanation])))
        ->toThrow(QueryException::class, 'work_support_requests_explanation_check');
})->with(['', '   ', "\t", "\n", "\r\n", "\t\n ", "  \t  \r\n  "]);

it('refuses a status outside the six controlled states', function (): void {
    // OI-11 fixed the vocabulary; `under_review` is the state the Client
    // deliberately did not adopt, so it is the honest thing to test with.
    expect(fn () => DB::table('work_support_requests')->insert(wsrRow(['status' => 'under_review'])))
        ->toThrow(QueryException::class, 'work_support_requests_status_check');
});

it('refuses a decline with no reason', function (?string $reason): void {
    expect(fn () => DB::table('work_support_requests')->insert(wsrRow([
        'status' => WorkSupportStatus::Declined->value,
        'decided_at' => now(),
        'decline_reason' => $reason,
    ])))->toThrow(QueryException::class, 'work_support_requests_decline_reason_check');
})->with([null, '', '   ', "\t", "\r\n"]);

it('accepts a decline that carries a reason', function (): void {
    $id = DB::table('work_support_requests')->insertGetId(wsrRow([
        'status' => WorkSupportStatus::Declined->value,
        'decided_by' => $this->technician->id,
        'decided_at' => now(),
        'decline_reason' => 'No budget for a replacement unit this quarter.',
    ]));

    expect(DB::table('work_support_requests')->where('id', $id)->value('decline_reason'))
        ->toBe('No budget for a replacement unit this quarter.');
});

it('refuses a decision with no decided_at', function (string $status): void {
    $row = wsrRow(['status' => $status, 'decided_at' => null]);

    if ($status === WorkSupportStatus::Declined->value) {
        $row['decline_reason'] = 'A reason, so the decline CHECK is not what fires.';
    }

    expect(fn () => DB::table('work_support_requests')->insert($row))
        ->toThrow(QueryException::class, 'work_support_requests_decided_at_check');
})->with([WorkSupportStatus::Approved->value, WorkSupportStatus::Declined->value]);

it('refuses a cancellation with no cancelled_at', function (): void {
    expect(fn () => DB::table('work_support_requests')->insert(wsrRow([
        'status' => WorkSupportStatus::Cancelled->value,
        'cancelled_at' => null,
    ])))->toThrow(QueryException::class, 'work_support_requests_cancelled_at_check');
});

it('survives deletion of the deciding administrator', function (): void {
    /*
     * The reason `work_support_requests_decided_at_check` keys on `decided_at`
     * and not on `decided_by`. Deleting the decider issues an UPDATE against
     * this row (ON DELETE SET NULL), which re-evaluates every CHECK on it. Had
     * the constraint named `decided_by`, a routine account purge would fail
     * with a constraint violation — and the fix would have been to weaken the
     * audit, not the constraint. The deciding actor lives in `activity_logs`.
     */
    $admin = User::factory()->create();

    $id = DB::table('work_support_requests')->insertGetId(wsrRow([
        'status' => WorkSupportStatus::Approved->value,
        'decided_by' => $admin->id,
        'decided_at' => now(),
        'rescheduled_to' => now()->addWeek(),
    ]));

    $admin->forceDelete();

    $row = DB::table('work_support_requests')->where('id', $id)->first();

    expect($row)->not->toBeNull()
        ->and($row->decided_by)->toBeNull()
        ->and($row->status)->toBe(WorkSupportStatus::Approved->value);
});

/*
 * These two are deliberately separate tests rather than one.
 *
 * A failed statement aborts the enclosing Postgres transaction (SQLSTATE
 * 25P02), and `RefreshDatabase` wraps each test in exactly one. So a test that
 * asserts a rejection and then goes on to insert a valid row is not testing two
 * rules — it is testing one rule and then reporting the poisoned transaction as
 * a second, unrelated failure. One assertion of rejection per test.
 */
it('requires a pc unit', function (): void {
    // FR-WSR-001: a request must always name a machine, even when it names no
    // ticket. NOT NULL is what makes that structural.
    expect(fn () => DB::table('work_support_requests')->insert(wsrRow(['pc_unit_id' => null])))
        ->toThrow(QueryException::class);
});

it('protects the pc unit from deletion while a request references it', function (): void {
    DB::table('work_support_requests')->insert(wsrRow());

    // RESTRICT: a hard delete of the anchor must not orphan the request.
    expect(fn () => DB::table('pc_units')->where('id', $this->pcUnit->id)->delete())
        ->toThrow(QueryException::class, 'work_support_requests_pc_unit_id_foreign');
});

it('leaves ticket and maintenance context optional', function (): void {
    $id = DB::table('work_support_requests')->insertGetId(wsrRow([
        'ticket_id' => null,
        'maintenance_record_id' => null,
    ]));

    // FR-WSR-001: "A request unrelated to any ticket shall still be permitted,
    // provided it names a PC unit."
    expect(DB::table('work_support_requests')->where('id', $id)->exists())->toBeTrue();
});

/* --------------------------------------- work_support_request_items (M3) */

it('refuses a line item with a non-positive quantity', function (int $quantity): void {
    $requestId = DB::table('work_support_requests')->insertGetId(wsrRow());

    expect(fn () => DB::table('work_support_request_items')->insert([
        'work_support_request_id' => $requestId,
        'description' => 'ATX power supply, 500W',
        'quantity' => $quantity,
        'created_at' => now(),
        'updated_at' => now(),
    ]))->toThrow(QueryException::class, 'work_support_request_items_quantity_check');
})->with([0, -1]);

it('refuses a line item that names neither a catalog model nor a description', function (?string $description): void {
    $requestId = DB::table('work_support_requests')->insertGetId(wsrRow());

    expect(fn () => DB::table('work_support_request_items')->insert([
        'work_support_request_id' => $requestId,
        'hardware_model_id' => null,
        'description' => $description,
        'quantity' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ]))->toThrow(QueryException::class, 'work_support_request_items_named_check');
})->with([null, '', '   ', "\t", "\r\n"]);

it('accepts a free-text line item', function (): void {
    $requestId = DB::table('work_support_requests')->insertGetId(wsrRow());

    DB::table('work_support_request_items')->insert([
        'work_support_request_id' => $requestId,
        'description' => 'Thermal paste',
        'quantity' => 2,
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    expect(DB::table('work_support_request_items')->where('work_support_request_id', $requestId)->count())
        ->toBe(1);
});

/* ------------------------------ work_support_request_attachments (M4) */

it('refuses an attachment kind outside the display split', function (): void {
    $requestId = DB::table('work_support_requests')->insertGetId(wsrRow());

    expect(fn () => DB::table('work_support_request_attachments')->insert([
        'work_support_request_id' => $requestId,
        'kind' => 'executable',
        'storage_path' => 'work-support/x/file.png',
        'original_filename' => 'file.png',
        'created_at' => now(),
        'updated_at' => now(),
    ]))->toThrow(QueryException::class, 'work_support_request_attachments_kind_check');
});

it('refuses a negative attachment file size', function (): void {
    $requestId = DB::table('work_support_requests')->insertGetId(wsrRow());

    expect(fn () => DB::table('work_support_request_attachments')->insert([
        'work_support_request_id' => $requestId,
        'kind' => 'image',
        'storage_path' => 'work-support/x/file.png',
        'original_filename' => 'file.png',
        'file_size' => -1,
        'created_at' => now(),
        'updated_at' => now(),
    ]))->toThrow(QueryException::class, 'work_support_request_attachments_file_size_check');
});

it('carries the four attachment security columns the trust boundary needs', function (): void {
    // FR-WSR-003 / DD-53: evidence goes through AttachmentSecurity, which needs
    // somewhere to record the server-detected type and the checksum. DR-021
    // added these to `repair_images` for exactly this reason; a table that
    // cannot record them cannot sit behind the same boundary.
    foreach (['original_filename', 'mime_type', 'file_size', 'checksum'] as $column) {
        expect(Schema::hasColumn('work_support_request_attachments', $column))
            ->toBeTrue("work_support_request_attachments is missing {$column}");
    }
});

/* ------------------------------------------------------------- cascades */

it('takes items and attachments with the request when it is deleted', function (): void {
    $requestId = DB::table('work_support_requests')->insertGetId(wsrRow());

    DB::table('work_support_request_items')->insert([
        'work_support_request_id' => $requestId,
        'description' => 'RAM module',
        'quantity' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    DB::table('work_support_request_attachments')->insert([
        'work_support_request_id' => $requestId,
        'kind' => 'image',
        'storage_path' => 'work-support/x/photo.jpg',
        'original_filename' => 'photo.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ]);

    DB::table('work_support_requests')->where('id', $requestId)->delete();

    expect(DB::table('work_support_request_items')->where('work_support_request_id', $requestId)->count())->toBe(0)
        ->and(DB::table('work_support_request_attachments')->where('work_support_request_id', $requestId)->count())->toBe(0);
});

it('does not touch the procurement request vocabulary', function (): void {
    // OI-09: `procurement_requests` shall be neither overloaded nor redesigned.
    // The bridge is one nullable column on *our* table, pointing outwards.
    expect(Schema::hasColumn('work_support_requests', 'procurement_request_id'))->toBeTrue()
        ->and(Schema::hasColumn('procurement_requests', 'pc_unit_id'))->toBeFalse()
        ->and(Schema::hasColumn('procurement_requests', 'ticket_id'))->toBeFalse()
        ->and(Schema::hasColumn('procurement_requests', 'maintenance_record_id'))->toBeFalse();

    $check = DB::selectOne(<<<'SQL'
        SELECT pg_get_constraintdef(oid) AS def
        FROM pg_constraint
        WHERE conname = 'procurement_requests_status_check'
    SQL);

    // The purchasing lifecycle is unchanged: no `clarification_requested`, no
    // reschedule semantics leaked into it.
    expect($check?->def ?? '')->not->toContain('clarification_requested');
});
